silver_layer:
  outputs:
    dev:
      catalog: dev_julia
      host: "{{ env_var('DBT_HOST') }}"
      http_path: "{{ env_var('DBT_WAREHOUSE') }}"
      schema: silver
      threads: 1
      token: "{{ env_var('DBT_ACCESS_TOKEN') }}"
      type: databricks
  target: dev